language: go
    
before_install:
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
#  - echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> /home/travis/.bash_profile
  - eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)  
  - brew install hugo

script:
  - hugo -D # Builds the website on travis

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: oculartechie/oculartechie.github.io # Repo to deploy site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
