# DO NOT REMOVE THIS
theme        = "hello-friend" 

# Override these settings with your own
title        = "oculartechie"
languageCode = "en-us"
baseURL      = "https://oculartechie.github.io/"
copyright    = "© 2021"
paginate     = 10

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    title = "Life through the eyes of a modern day nerd"
    subtitle = "Stay tuned....."
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "hello everybody!"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"


    # Social icons
    [[languages.en.params.social]]
      name = "twitter"
      url  = "https://twitter.com/oculartechie"

    [[languages.en.params.social]]
      name = "github"
      url  = "https://github.com/oculartechie"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        title = "About"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "blog"
        title = "Blog"
        url = "/blog"
