# .github/workflows/github-actions-hugo-deploy.yml

name: build

on:
  push:
    branches:
    - default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Building...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: oculartechie/oculartechie.github.io
        DEPLOY_BRANCH: default
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: America/Toronto

